### ISSUE TITLE
rdf.json is missing

### ISSUE THREAD

**Issue by musicEnfanthen** [thomsonreuters/AtomOntologyCompleter#1]
Thanks a lot for this auto completion!

The `rdf.json` file is missing in `./lib/ontologies` .

Tried to add it to your repo and convert from turtle file (http://www.w3.org/1999/02/22-rdf-syntax-ns#), but got the following error:

```
cat rdf.ttl | python convert.py "http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf > rdf.json
  File "convert.py", line 25
    predicateRegex = re.compile(ur'^([^:\s]*):([a-zA-Z\-_]+)')
                                                            ^
SyntaxError: invalid syntax

```

Did I miss something?

**Comment by TRnonodename** [comment]
Yes it is! I’m kicking myself that I missed this. Have a look at the repo and you’ll see I’ve already checked in... I thought I had fixed with a patch to 1.4.1 but will check.

What os and python version are you running ? That .py works for me



________________________________

**Comment by musicEnfanthen** [comment]
Running Windows 10 and python 3.6.5. Switching to python 2 did the trick, the `convert.py` finished without any problems now. If you want, I can provide a patch for the missing `rdf.json` file.

**Comment by TRnonodename** [comment]
That's very kind of you. I've changed my process so no more of these can get missed. 1.4.2 adds rdf.json and I've updated convert.py to indicate the python version. Thanks for the offer (and thanks for confirming this works on Windows ;-)

**Comment by musicEnfanthen** [comment]
Yes, indeed it works on Windows ;). Thanks for including the missing file and your work.
